#!/usr/bin/env bash
# =============================================================================
# gen_diesel_types.sh — Generate Diesel schema types from a running database
# =============================================================================
#
# Intended for development / CI.  Connects to the PostgreSQL instance
# specified by DATABASE_URL, introspects the `app` schema, and emits:
#   - src/schema.rs              (Diesel table declarations)
#   - src/schema_models.rs       (Queryable / Insertable structs)
#   - src/schema_enums.rs        (Rust enums from pg_enum)
#   - src/schema_enums_impls.rs  (Display & FromStr impls for enums)
#
# Prerequisites:
#   - diesel_cli  (cargo install diesel_cli --no-default-features --features postgres)
#   - psql        (PostgreSQL client)
#   - awk
#
# Usage:
#   DATABASE_URL="postgresql://postgres:password@localhost:5432/moshsplit" \
#     ./gen_diesel_types.sh
# =============================================================================

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
DATABASE_URL="${DATABASE_URL:-postgresql://postgres:password@0.0.0.0:5432/moshsplit}"
OUTPUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

SCHEMA_RS="${OUTPUT_DIR}/src/schema.rs"
SCHEMA_MODELS="${OUTPUT_DIR}/src/schema_models.rs"
SCHEMA_ENUMS="${OUTPUT_DIR}/src/schema_enums.rs"
SCHEMA_ENUMS_IMPLS="${OUTPUT_DIR}/src/schema_enums_impls.rs"

# Ensure required tooling is available
command -v diesel >/dev/null 2>&1 || {
    echo "ERROR: 'diesel' CLI not found. Install with:"
    echo "  cargo install diesel_cli --no-default-features --features postgres"
    exit 1
}
command -v psql >/dev/null 2>&1 || {
    echo "ERROR: 'psql' not found. Install the PostgreSQL client."
    exit 1
}

# Ensure the output directory exists
mkdir -p "$(dirname "${SCHEMA_RS}")"

# ── Helper: run a SQL query against the target database ──────────────────────
sql() {
    psql "${DATABASE_URL}" -t -A "$@"
}

# ── 1. Generate schema.rs via Diesel CLI ─────────────────────────────────────
echo "==> Generating ${SCHEMA_RS} ..."
diesel print-schema \
    --database-url "${DATABASE_URL}" \
    --schema app \
    --patch-file "${OUTPUT_DIR}/src/schema.patch" \
    > "${SCHEMA_RS}"

echo "     ✓ schema.rs generated"

# ── 2. Generate schema_models.rs ──────────────────────────────────────────────
# Build Queryable / Insertable structs for each table in the `app` schema.
echo "==> Generating ${SCHEMA_MODELS} ..."

cat > "${SCHEMA_MODELS}" <<-'EOF'
// ---------------------------------------------------------------------------
// schema_models.rs  —  Auto-generated Diesel entity structs
// Generated by scripts/gen_diesel_types.sh  —  DO NOT EDIT BY HAND
// ---------------------------------------------------------------------------

use crate::schema::app;
use crate::schema_enums::{EventImageType, EventMemberRole, EventStatus, ExpenseType, SettlementStatus, SplitType};
use diesel::prelude::*;

EOF

# Discover public tables (excluding diesel metadata tables)
TABLES=$(sql -c "
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'app'
      AND table_type = 'BASE TABLE'
      AND table_name NOT LIKE '__diesel_%'
    ORDER BY table_name;
")

for table in ${TABLES}; do
    # Skip the sqlx migration tracking table
    [ "${table}" = "_sqlx_migrations" ] && continue

    # Get column info: name, is_nullable, data_type
    COLUMNS=$(sql -c "
        SELECT column_name,
               CASE WHEN is_nullable = 'YES' THEN 'Option<' ELSE '' END,
               CASE
                   WHEN data_type = 'integer'               THEN 'i32'
                   WHEN data_type = 'bigint'                THEN 'i64'
                   WHEN data_type = 'smallint'              THEN 'i16'
                   WHEN data_type = 'boolean'               THEN 'bool'
                   WHEN data_type = 'text'                  THEN 'String'
                   WHEN data_type = 'varchar'               THEN 'String'
                   WHEN data_type = 'timestamp'             THEN 'chrono::NaiveDateTime'
                   WHEN data_type = 'timestamp with time zone' THEN 'chrono::DateTime<chrono::Utc>'
                   WHEN data_type = 'date'                  THEN 'chrono::NaiveDate'
                   WHEN data_type = 'time'                  THEN 'chrono::NaiveTime'
                   WHEN data_type = 'numeric'               THEN 'rust_decimal::Decimal'
                   WHEN data_type = 'double precision'      THEN 'f64'
                   WHEN data_type = 'real'                  THEN 'f32'
                   WHEN data_type = 'uuid'                  THEN 'uuid::Uuid'
                   WHEN data_type = 'jsonb'                 THEN 'serde_json::Value'
                   WHEN data_type = 'json'                  THEN 'serde_json::Value'
                   WHEN data_type = 'bytea'                 THEN 'Vec<u8>'
                   WHEN udt_name = 'event_status'           THEN 'crate::schema_enums::EventStatus'
                   WHEN udt_name = 'event_member_role'      THEN 'crate::schema_enums::EventMemberRole'
                   WHEN udt_name = 'split_type'             THEN 'crate::schema_enums::SplitType'
                   WHEN udt_name = 'settlement_status'      THEN 'crate::schema_enums::SettlementStatus'
                   WHEN udt_name = 'expense_type'           THEN 'crate::schema_enums::ExpenseType'
                   WHEN udt_name = 'event_image_type'       THEN 'crate::schema_enums::EventImageType'
                   ELSE 'String'  -- fallback
               END,
               CASE WHEN is_nullable = 'YES' THEN '>' ELSE '' END
        FROM information_schema.columns
        WHERE table_schema = 'app'
          AND table_name = '${table}'
        ORDER BY ordinal_position;
    ")

    # Convert snake_case table name to CamelCase for struct name
    struct_name=$(echo "${table}" | awk -F'_' '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1' OFS='')

    # Build the Rust struct
    {
        echo "#[derive(Debug, Clone, Queryable, Insertable)]"
        echo "#[diesel(table_name = app::${table})]"
        echo "pub struct ${struct_name} {"
        while IFS='|' read -r col_name nullable rust_type close; do
            echo "    pub ${col_name}: ${nullable}${rust_type}${close},"
        done <<< "${COLUMNS}"
        echo "}"
        echo ""
    } >> "${SCHEMA_MODELS}"
done

echo "     ✓ schema_models.rs generated"

# ── 3. Generate schema_enums.rs ───────────────────────────────────────────────
# SKIPPED: schema_enums.rs is hand-written (uses manual FromSql/ToSql impls
# for Diesel + PostgreSQL native enums). See src/schema_enums.rs.
echo "==> Skipping ${SCHEMA_ENUMS} (hand-written)"

# ── 4. Generate schema_enums_impls.rs ─────────────────────────────────────────
# SKIPPED: schema_enums_impls.rs is hand-written.
echo "==> Skipping ${SCHEMA_ENUMS_IMPLS} (hand-written)"
echo ""
echo "Done. Generated files:"
echo "  • ${SCHEMA_RS}"
echo "  • ${SCHEMA_MODELS}"
echo "  • ${SCHEMA_ENUMS}"
echo "  • ${SCHEMA_ENUMS_IMPLS}"
