#!/usr/bin/env bash
# =============================================================================
# gen_diesel_types.sh — Generate Diesel schema types from a running database
# =============================================================================
#
# Intended for development / CI.  Connects to the PostgreSQL instance
# specified by DATABASE_URL, introspects the `app` schema, and emits:
#   - src/schema.rs              (Diesel table declarations)
#   - src/schema_models.rs       (Queryable / Insertable structs)
#   - src/schema_enums.rs        (Rust enums from pg_enum)
#   - src/schema_enums_impls.rs  (Display & FromStr impls for enums)
#
# Prerequisites:
#   - diesel_cli  (cargo install diesel_cli --no-default-features --features postgres)
#   - psql        (PostgreSQL client)
#   - awk
#
# Usage:
#   DATABASE_URL="postgresql://postgres:password@localhost:5432/moshsplit" \
#     ./gen_diesel_types.sh
# =============================================================================

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
DATABASE_URL="${DATABASE_URL:-postgresql://postgres:password@0.0.0.0:5432/moshsplit}"
OUTPUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

SCHEMA_RS="${OUTPUT_DIR}/src/schema.rs"
SCHEMA_MODELS="${OUTPUT_DIR}/src/schema_models.rs"
SCHEMA_ENUMS="${OUTPUT_DIR}/src/schema_enums.rs"
SCHEMA_ENUMS_IMPLS="${OUTPUT_DIR}/src/schema_enums_impls.rs"

# Ensure required tooling is available
command -v diesel >/dev/null 2>&1 || {
    echo "ERROR: 'diesel' CLI not found. Install with:"
    echo "  cargo install diesel_cli --no-default-features --features postgres"
    exit 1
}
command -v psql >/dev/null 2>&1 || {
    echo "ERROR: 'psql' not found. Install the PostgreSQL client."
    exit 1
}

# Ensure the output directory exists
mkdir -p "$(dirname "${SCHEMA_RS}")"

# ── Helper: run a SQL query against the target database ──────────────────────
sql() {
    psql "${DATABASE_URL}" -t -A "$@"
}

# ── 1. Generate schema.rs via Diesel CLI ─────────────────────────────────────
echo "==> Generating ${SCHEMA_RS} ..."
diesel print-schema \
    --database-url "${DATABASE_URL}" \
    --schema app \
    --patch-file "${OUTPUT_DIR}/src/schema.patch" \
    > "${SCHEMA_RS}"

echo "     ✓ schema.rs generated"

# ── 2. Generate schema_models.rs ──────────────────────────────────────────────
# Build Queryable / Insertable structs for each table in the `app` schema.
echo "==> Generating ${SCHEMA_MODELS} ..."

cat > "${SCHEMA_MODELS}" <<-'EOF'
// ---------------------------------------------------------------------------
// schema_models.rs  —  Auto-generated Diesel entity structs
// Generated by scripts/gen_diesel_types.sh  —  DO NOT EDIT BY HAND
// ---------------------------------------------------------------------------

EOF

# Discover public tables (excluding diesel metadata tables)
TABLES=$(sql -c "
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'app'
      AND table_type = 'BASE TABLE'
      AND table_name NOT LIKE '__diesel_%'
    ORDER BY table_name;
")

for table in ${TABLES}; do
    # Get column info: name, is_nullable, data_type
    COLUMNS=$(sql -c "
        SELECT column_name,
               CASE WHEN is_nullable = 'YES' THEN 'Option<' ELSE '' END,
               CASE
                   WHEN data_type = 'integer'      THEN 'i32'
                   WHEN data_type = 'bigint'       THEN 'i64'
                   WHEN data_type = 'smallint'     THEN 'i16'
                   WHEN data_type = 'boolean'      THEN 'bool'
                   WHEN data_type = 'text'         THEN 'String'
                   WHEN data_type = 'varchar'      THEN 'String'
                   WHEN data_type = 'timestamp'    THEN 'chrono::NaiveDateTime'
                   WHEN data_type = 'timestamptz'  THEN 'chrono::DateTime<chrono::Utc>'
                   WHEN data_type = 'date'        THEN 'chrono::NaiveDate'
                   WHEN data_type = 'time'        THEN 'chrono::NaiveTime'
                   WHEN data_type = 'numeric'     THEN 'rust_decimal::Decimal'
                   WHEN data_type = 'double precision' THEN 'f64'
                   WHEN data_type = 'real'        THEN 'f32'
                   WHEN data_type = 'uuid'        THEN 'uuid::Uuid'
                   WHEN data_type = 'jsonb'       THEN 'serde_json::Value'
                   WHEN data_type = 'json'        THEN 'serde_json::Value'
                   WHEN data_type = 'bytea'       THEN 'Vec<u8>'
                   ELSE 'String'  -- fallback
               END,
               CASE WHEN is_nullable = 'YES' THEN '>' ELSE '' END
        FROM information_schema.columns
        WHERE table_schema = 'app'
          AND table_name = '${table}'
        ORDER BY ordinal_position;
    ")

    # Build the Rust struct
    {
        echo "#[derive(Debug, Clone, Queryable, Insertable, AsChangeset)]"
        echo "#[diesel(table_name = ${table})]"
        echo "pub struct ${table^} {"
        while IFS='|' read -r col_name nullable rust_type close; do
            echo "    pub ${col_name}: ${nullable}${rust_type}${close},"
        done <<< "${COLUMNS}"
        echo "}"
        echo ""
    } >> "${SCHEMA_MODELS}"
done

echo "     ✓ schema_models.rs generated"

# ── 3. Generate schema_enums.rs ───────────────────────────────────────────────
# Introspect PostgreSQL custom enum types defined in the `app` schema.
echo "==> Generating ${SCHEMA_ENUMS} ..."

cat > "${SCHEMA_ENUMS}" <<-'EOF'
// ---------------------------------------------------------------------------
// schema_enums.rs  —  Auto-generated Rust enums from PostgreSQL pg_enum
// Generated by scripts/gen_diesel_types.sh  —  DO NOT EDIT BY HAND
// ---------------------------------------------------------------------------

EOF

ENUMS=$(sql -c "
    SELECT t.typname AS enum_name,
           array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    JOIN pg_enum e ON t.oid = e.enumtypid
    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'app'
    GROUP BY t.typname;
")

while IFS='|' read -r enum_name labels; do
    # Convert label string like "{active,pending,archived}" into Rust variants
    # Remove surrounding braces and split on comma
    labels_clean="${labels#'{'}"
    labels_clean="${labels_clean%'}'}"

    {
        echo "#[derive(Debug, Clone, PartialEq, Eq, diesel::FromSqlRow, diesel::AsExpression)]"
        echo "#[diesel(sql_type = diesel::sql_types::Text)]"
        echo "pub enum ${enum_name^} {"
        IFS=',' read -ra variants <<< "${labels_clean}"
        for variant in "${variants[@]}"; do
            # Capitalise first letter for Rust variant name
            variant_rust="$(echo "${variant}" | sed 's/^\(.\)/\U\1/')"
            echo "    ${variant_rust},"
        done
        echo "}"
        echo ""
    }
done <<< "${ENUMS}" >> "${SCHEMA_ENUMS}"

echo "     ✓ schema_enums.rs generated"

# ── 4. Generate schema_enums_impls.rs ─────────────────────────────────────────
echo "==> Generating ${SCHEMA_ENUMS_IMPLS} ..."

cat > "${SCHEMA_ENUMS_IMPLS}" <<-'EOF'
// ---------------------------------------------------------------------------
// schema_enums_impls.rs  —  Auto-generated Display & FromStr for DB enums
// Generated by scripts/gen_diesel_types.sh  —  DO NOT EDIT BY HAND
// ---------------------------------------------------------------------------

EOF

while IFS='|' read -r enum_name labels; do
    labels_clean="${labels#'{'}"
    labels_clean="${labels_clean%'}'}"

    {
        echo "impl std::fmt::Display for ${enum_name^} {"
        echo "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {"
        echo "        match self {"
        IFS=',' read -ra variants <<< "${labels_clean}"
        for variant in "${variants[@]}"; do
            variant_rust="$(echo "${variant}" | sed 's/^\(.\)/\U\1/')"
            echo "            Self::${variant_rust} => write!(f, \"${variant}\"),"
        done
        echo "        }"
        echo "    }"
        echo "}"
        echo ""
    }
done <<< "${ENUMS}" >> "${SCHEMA_ENUMS_IMPLS}"

echo "     ✓ schema_enums_impls.rs generated"
echo ""
echo "Done. Generated files:"
echo "  • ${SCHEMA_RS}"
echo "  • ${SCHEMA_MODELS}"
echo "  • ${SCHEMA_ENUMS}"
echo "  • ${SCHEMA_ENUMS_IMPLS}"
