// ---------------------------------------------------------------------------
// schema_models.rs  —  Auto-generated Diesel entity structs
// Generated by scripts/gen_diesel_types.sh  —  DO NOT EDIT BY HAND
// ---------------------------------------------------------------------------

use crate::schema::app;
use crate::schema_enums::{EventImageType, EventMemberRole, EventStatus, ExpenseType, SettlementStatus, SplitType};
use diesel::prelude::*;

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::audit_log)]
pub struct AuditLog {
    pub id: uuid::Uuid,
    pub action: String,
    pub entity_type: String,
    pub entity_id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    pub details: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::event)]
pub struct Event {
    pub id: uuid::Uuid,
    pub name: String,
    pub description: Option<String>,
    pub currency: String,
    pub status: EventStatus,
    pub created_by: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::event_image)]
pub struct EventImage {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub url: String,
    pub alt_text: Option<String>,
    pub image_type: EventImageType,
    pub sort_order: i32,
    pub uploaded_at: chrono::DateTime<chrono::Utc>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::event_member)]
pub struct EventMember {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    pub role: EventMemberRole,
    pub joined_at: chrono::DateTime<chrono::Utc>,
    pub left_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::expense)]
pub struct Expense {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub created_by: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub current_version_id: Option<uuid::Uuid>,
    pub deleted_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::expense_version)]
pub struct ExpenseVersion {
    pub id: uuid::Uuid,
    pub expense_id: uuid::Uuid,
    pub version_number: i32,
    pub title: String,
    pub description: Option<String>,
    pub amount_cents: i32,
    pub paid_by: uuid::Uuid,
    pub split_type: SplitType,
    pub split_data: serde_json::Value,
    pub notes: Option<String>,
    pub created_by: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub expense_type: Option<ExpenseType>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::expense_version_share)]
pub struct ExpenseVersionShare {
    pub id: uuid::Uuid,
    pub expense_version_id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    pub share_cents: i32,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::payment)]
pub struct Payment {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub from_user: uuid::Uuid,
    pub to_user: uuid::Uuid,
    pub amount_cents: i32,
    pub currency: String,
    pub description: Option<String>,
    pub payment_method: Option<String>,
    pub external_ref: Option<String>,
    pub recorded_by: uuid::Uuid,
    pub recorded_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::settlement)]
pub struct Settlement {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub from_user: uuid::Uuid,
    pub to_user: uuid::Uuid,
    pub amount_cents: i32,
    pub status: SettlementStatus,
    pub settled_at: Option<chrono::DateTime<chrono::Utc>>,
    pub created_by: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

