// ---------------------------------------------------------------------------
// schema_models.rs  —  Auto-generated Diesel entity structs
// Generated by scripts/gen_diesel_types.sh  —  DO NOT EDIT BY HAND
// ---------------------------------------------------------------------------

use crate::schema::app;
use diesel::prelude::*;

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::audit_log)]
pub struct AuditLog {
    pub id: uuid::Uuid,
    pub action: String,
    pub entity_type: String,
    pub entity_id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    pub details: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::event)]
pub struct Event {
    pub id: uuid::Uuid,
    pub name: String,
    pub description: Option<String>,
    pub currency: String,
    pub status: crate::schema_enums::EventStatus,
    pub created_by: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::event_image)]
pub struct EventImage {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub url: String,
    pub alt_text: Option<String>,
    pub image_type: crate::schema_enums::EventImageType,
    pub sort_order: i32,
    pub uploaded_at: chrono::DateTime<chrono::Utc>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::event_member)]
pub struct EventMember {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    pub role: crate::schema_enums::EventMemberRole,
    pub joined_at: chrono::DateTime<chrono::Utc>,
    pub left_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::expense)]
pub struct Expense {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub created_by: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub current_version_id: Option<uuid::Uuid>,
    pub deleted_at: Option<chrono::DateTime<chrono::Utc>>,
    pub deletion_status: Option<String>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::expense_version)]
pub struct ExpenseVersion {
    pub id: uuid::Uuid,
    pub expense_id: uuid::Uuid,
    pub version_number: i32,
    pub title: String,
    pub description: Option<String>,
    pub amount_cents: i32,
    pub paid_by: uuid::Uuid,
    pub split_type: crate::schema_enums::SplitType,
    pub split_data: serde_json::Value,
    pub notes: Option<String>,
    pub created_by: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub expense_type: Option<crate::schema_enums::ExpenseType>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::expense_version_share)]
pub struct ExpenseVersionShare {
    pub id: uuid::Uuid,
    pub expense_version_id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    pub share_cents: i32,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::payment)]
pub struct Payment {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub creditor_id: uuid::Uuid,
    pub debtor_id: uuid::Uuid,
    pub expense_id: Option<uuid::Uuid>,
    pub amount_cents: i32,
    pub amount_paid_cents: i32,
    pub reason: String,
    pub status: crate::schema_enums::PaymentStatus,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::credit)]
pub struct Credit {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub creditor_id: uuid::Uuid,
    pub debtor_id: uuid::Uuid,
    pub amount_cents: i32,
    pub amount_used_cents: i32,
    pub source_expense_id: Option<uuid::Uuid>,
    pub status: crate::schema_enums::CreditStatus,
    pub version: i32,
    pub parent_credit_id: Option<uuid::Uuid>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Queryable, Insertable)]
#[diesel(table_name = app::payment_transaction)]
pub struct PaymentTransaction {
    pub id: uuid::Uuid,
    pub payment_id: uuid::Uuid,
    pub amount_cents: i32,
    pub status: crate::schema_enums::PaymentTransactionStatus,
    pub proposed_by: uuid::Uuid,
    pub confirmed_by: Option<uuid::Uuid>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub confirmed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub payment_method: String,
    pub credit_id: Option<uuid::Uuid>,
}
